const User=require('../models/User'), send=require('../utils/sendToken'), passport=require('passport'), jwt=require('jsonwebtoken');
exports.register = async(req,res,next)=>{ try{ const{name,email,password,accountType,companyName,city}=req.body; if(await User.findOne({email:email.toLowerCase()})) return res.status(400).json({success:false,message:'Email ekziston.'}); send(await User.create({name,email,password,accountType,city,...(accountType==='company'&&companyName?{companyName}:{})}),201,res); }catch(e){next(e);} };
exports.login = (req,res,next) => passport.authenticate('local',{session:false},(err,user,info)=>{ if(err) return next(err); if(!user) return res.status(401).json({success:false,message:info?.message||'Kredenciale të gabuara.'}); send(user,200,res); })(req,res,next);
exports.googleAuth = passport.authenticate('google',{scope:['profile','email'],session:false});
exports.googleCallback = (req,res,next) => passport.authenticate('google',{session:false},(err,user)=>{ try{ if(err||!user) return res.redirect(`${process.env.CLIENT_URL}?error=google_failed`); const t=jwt.sign({id:user._id,role:user.role,accountType:user.accountType},process.env.JWT_SECRET,{expiresIn:'7d'}); res.cookie('token',t,{expires:new Date(Date.now()+7*24*60*60*1000),httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'None':'Lax'}).redirect(`${process.env.CLIENT_URL}?token=${t}`); }catch(e){next(e);} })(req,res,next);
exports.logout = (_,res)=>{ res.cookie('token','none',{expires:new Date(Date.now()+5000),httpOnly:true}); res.json({success:true}); };
exports.getMe = async(req,res)=>{ const u=await User.findById(req.user.id).populate('savedListings','title price city coverImage'); res.json({success:true,user:u}); };
exports.updateProfile = async(req,res,next)=>{ try{ const f=['name','phone','city','companyName']; const u={}; f.forEach(k=>{if(req.body[k]!==undefined)u[k]=req.body[k];}); res.json({success:true,user:await User.findByIdAndUpdate(req.user.id,u,{new:true})}); }catch(e){next(e);} };
exports.changePassword = async(req,res,next)=>{ try{ const{currentPassword,newPassword}=req.body; if(!currentPassword||!newPassword) return res.status(400).json({success:false,message:'Të dy fjalëkalimet janë të detyrueshme.'}); if(newPassword.length<8) return res.status(400).json({success:false,message:'Fjalëkalimi i ri duhet të ketë të paktën 8 karaktere.'}); const user=await User.findById(req.user.id).select('+password'); if(!user.password) return res.status(400).json({success:false,message:'Llogaria juaj nuk ka fjalëkalim (Google OAuth).'}); const bcrypt=require('bcryptjs'); const ok=await bcrypt.compare(currentPassword,user.password); if(!ok) return res.status(401).json({success:false,message:'Fjalëkalimi aktual është i gabuar.'}); user.password=newPassword; await user.save(); res.json({success:true,message:'Fjalëkalimi u ndryshua me sukses.'}); }catch(e){next(e);} };
