require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan');
const cookieParser=require('cookie-parser'),session=require('express-session'),MongoStore=require('connect-mongo');
const rateLimit=require('express-rate-limit'),connectDB=require('./config/db'),passport=require('./config/passport');
const errorHandler=require('./middleware/errorHandler');
connectDB();
const app=express();
app.use(helmet());
app.use(cors({origin:[process.env.CLIENT_URL,'http://localhost:3000','http://localhost:5001','http://127.0.0.1:5500','http://127.0.0.1:3000','null'],credentials:true,methods:['GET','POST','PUT','DELETE','OPTIONS']}));
app.use(rateLimit({windowMs:15*60*1000,max:500}));
app.use(express.json({limit:'10mb'}));
app.use(express.urlencoded({extended:true,limit:'10mb'}));
app.use(cookieParser());
if(process.env.NODE_ENV==='development') app.use(morgan('dev'));
app.use(session({secret:process.env.SESSION_SECRET||'secret',resave:false,saveUninitialized:false,store:MongoStore.create({mongoUrl:process.env.MONGO_URI,touchAfter:24*3600}),cookie:{httpOnly:true,secure:false,maxAge:7*24*60*60*1000}}));
app.use(passport.initialize());
app.use(passport.session());
app.get('/health',(req,res)=>res.json({success:true,message:'PronaKosova API is running 🏠',env:process.env.NODE_ENV}));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/listings',require('./routes/listings'));
app.use('/api/builders',require('./routes/builders'));
app.use('/api/inquiries',require('./routes/inquiries'));
app.use('/api/ads',require('./routes/ads'));
app.use((req,res)=>res.status(404).json({success:false,message:'Route not found'}));
app.use(errorHandler);
const PORT=process.env.PORT||5000;
const server=app.listen(PORT,()=>console.log(`\n🚀 http://localhost:${PORT}  |  Health: http://localhost:${PORT}/health\n`));
process.on('unhandledRejection',e=>{console.error('❌',e.message);server.close(()=>process.exit(1));});
module.exports=app;
